apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carental-ingress
spec:
  rules:
    - host: carental.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carental-service
                port:
                  number: 80
